version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: db
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./flyway/sql:/flyway/sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]

networks:
  backend:
    driver: bridge
